name: Generate Manifest

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'
          
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
        
      - name: Install packages
        run: |
          install.packages(c("shiny", "ggplot2", "gramEvol", "bslib", "rsconnect"), repos = "https://packagemanager.posit.co/cran/__linux__/jammy/latest")
        shell: Rscript {0}
        
      - name: Generate Manifest
        run: |
          rsconnect::writeManifest()
        shell: Rscript {0}
        
      - name: Commit and push manifest
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest.json
          git commit -m "Auto-generate manifest.json" || echo "No changes to commit"
          git push
